// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbKzMrJGhzS-xLVELOpinnGk0oiuNMA0w',
    appId: '1:1031129044635:web:84b251efc5e69e7ec2583e',
    messagingSenderId: '1031129044635',
    projectId: 'corsair3-87e85',
    authDomain: 'corsair3-87e85.firebaseapp.com',
    storageBucket: 'corsair3-87e85.appspot.com',
    measurementId: 'G-9Y35PHS5FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATeN9QczbvyrwSb2xOVU7qkE_63MYM_5A',
    appId: '1:1031129044635:android:dd6fcb4387ab43c3c2583e',
    messagingSenderId: '1031129044635',
    projectId: 'corsair3-87e85',
    storageBucket: 'corsair3-87e85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlr3FQhR7gGifBW0vlZ_KzTujAWVYtVr8',
    appId: '1:1031129044635:ios:1e3123958cb06c88c2583e',
    messagingSenderId: '1031129044635',
    projectId: 'corsair3-87e85',
    storageBucket: 'corsair3-87e85.appspot.com',
    iosClientId: '1031129044635-ob12kr5s16kj39qfm9cqeiamv92qgmc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flameGame',
  );
}
